name: 'KformPackage Action'
description: 'KformPackage Action, a release automation tool for kform providers and modules'
author: 'kform'

inputs:
  pkgDir:
    description: 'Directory from which the package is sourced'
    default: config
    required: false
  #refName:
  #  description: 'The short ref name of the branch or tag that triggered the workflow run'
  #  required: true
  #repository:
  #  description: 'The owner and repository name. For example, octocat/Hello-World'
  #  required: true
outputs:
  artifacts:
    description: 'Build result artifacts'

runs:
  using: composite
  steps:
  - run: go run main.go
    shell: bash
    env:
      INPUT_PKG_DIR: ${{ inputs.pkgDir }}
      INPUT_VERSION_TAG: ${{ inputs.versionTag }}