name: 'KformPackage Action'
description: 'KformPackage Action, a release automation tool for kform providers and modules using oci artifacts'
author: 'kform'

inputs:
  pkgDir:
    description: 'Directory from which the package is sourced'
    default: config
    required: false
outputs:
  artifacts:
    description: 'Build result artifacts'

runs:
  using: composite
  steps:
  - run: go run main.go
    shell: bash
    env:
      INPUT_PKG_DIR: ${{ inputs.pkgDir }}
      INPUT_VERSION_TAG: ${{ inputs.versionTag }}